# Generated by Django 4.0 on 2023-04-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='display_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Display name'),
        ),
    ]
